[package]
name = "fat32_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = { version = "0.9.23", features = ["map_physical_memory"] }

[[bin]]
name = "fat32_parser" 
path = "src/main.rs"
